name = "CompiledPermutations"
uuid = "fcb72232-d17c-42fb-b84b-29edb9b64290"
authors = ["Lilith Hafner <Lilith.Hafner@gmail.com> and contributors"]
version = "1.0.0"

[compat]
julia = "1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test"]
